# Jekyll configuration

name: Edward D. Kim
description: I am an assistant professor in the <a href="https://www.uwlax.edu/mathematics/">Department of Mathematics and Statistics</a> at the <a href="https://www.uwlax.edu/">University of Wisconsin-La Crosse</a> since Fall 2013. Here is my <a href="http://websites.uwlax.edu/ekim/edward_d_kim_cv.pdf">CV</a>.

# url is currently only used only for the RSS feed in feed.xml
url: http://edward-kim-math.github.io/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# blank to hide rss feed in top nav bar
rssfeed: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
